/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sample_delosreyes_project2;

import java.text.*;
import java.awt.print.*;
import javax.swing.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sample_delosreyes_project2.BST.Node;

/**
 *
 * @author Bezalel
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    BST bsttree = new BST();
    
    Object title[] = {"Fish Name","Price","Quantity","Owner","Pond Ownership","Number of farmers"};
    Object data[] = {null,null,null,null,null,null};
    String fishname, price, quantity, ownername, gender, pond, numoffarmers, sourcewater, msystem, csystem, fertilization;
    String searchelem;
    int intprice;
    
    Node temp;
    public MainMenu() {
        initComponents();
        AddPanel.setVisible(true);
        this.setTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        AddPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fishnametxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pricetxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        quantitytxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        gendertxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ownernametxt = new javax.swing.JTextField();
        pondtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        numoffarmerstxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sourcewatertxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        msystemtxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        csystemtxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fertilizationtxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Insertbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ViewTable = new javax.swing.JTable();
        dltbtn = new javax.swing.JButton();
        srchbtn = new javax.swing.JButton();
        searchtxt = new javax.swing.JTextField();
        viewbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        viewrangebtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jToggleButton1.setText("jToggleButton1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        AddPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Fish Name:");

        fishnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fishnametxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Price: ");

        jLabel4.setText("Quantity: ");

        jLabel5.setText("Owner's gender:");

        jLabel6.setText("Owner's name:");

        pondtxt.setText("e.g (Individual/Group)");

        jLabel7.setText("Pond Ownership:");

        jLabel8.setText("Number of farmers:");

        jLabel9.setText("Source of water:");

        sourcewatertxt.setText("e.g (Streams, Wells)");

        jLabel10.setText(" Management system: ");

        msystemtxt.setText("e.g (Extensive, etc.)");
        msystemtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msystemtxtActionPerformed(evt);
            }
        });

        jLabel11.setText("Culture system:");

        csystemtxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        csystemtxt.setText("e.g (Monoculture, Polyculture, etc)");
        csystemtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csystemtxtActionPerformed(evt);
            }
        });

        jLabel12.setText("Kinds of fertilization: ");

        fertilizationtxt.setText("e.g (Organic/Inorganic)");
        fertilizationtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fertilizationtxtActionPerformed(evt);
            }
        });

        jLabel13.setText("Fish Information");
        jLabel13.setToolTipText("");

        jLabel14.setText("Owner Information");
        jLabel14.setToolTipText("");

        jLabel15.setText("Management Information");
        jLabel15.setToolTipText("");

        Insertbtn.setText("INSERT");
        Insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertbtnActionPerformed(evt);
            }
        });

        ViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ViewTable);

        dltbtn.setText("DELETE");
        dltbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltbtnActionPerformed(evt);
            }
        });

        srchbtn.setText("SEARCH");
        srchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchbtnActionPerformed(evt);
            }
        });

        searchtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtxtActionPerformed(evt);
            }
        });

        viewbtn.setText("REFRESH");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample_delosreyes_project2/images/fish logo 1st.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 255));
        jLabel16.setText("FISH");

        jLabel17.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 255));
        jLabel17.setText("SYSTEM");

        jLabel18.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 255));
        jLabel18.setText("PRODUCT");
        jLabel18.setAlignmentY(0.1F);

        viewrangebtn.setText("VIEW BY RANGE");
        viewrangebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewrangebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddPanelLayout = new javax.swing.GroupLayout(AddPanel);
        AddPanel.setLayout(AddPanelLayout);
        AddPanelLayout.setHorizontalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPanelLayout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(srchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dltbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewrangebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(quantitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(fishnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gendertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(ownernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numoffarmerstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(pondtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(50, 50, 50)
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Insertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(AddPanelLayout.createSequentialGroup()
                                    .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(msystemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)
                                        .addComponent(sourcewatertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addGap(36, 36, 36)
                                    .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(csystemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)
                                        .addComponent(fertilizationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(48, 48, 48))
            .addGroup(AddPanelLayout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddPanelLayout.setVerticalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPanelLayout.createSequentialGroup()
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addGap(18, 18, 18)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPanelLayout.createSequentialGroup()
                                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(AddPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(csystemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fertilizationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(AddPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sourcewatertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(msystemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(Insertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pondtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8)
                                    .addGap(88, 88, 88))
                                .addGroup(AddPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ownernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gendertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numoffarmerstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fishnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srchbtn)
                    .addComponent(dltbtn)
                    .addComponent(viewrangebtn))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewbtn)
                .addGap(117, 117, 117))
        );

        jMenu1.setText("Open");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Open");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Save");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Print");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchbtnActionPerformed
       searchelem = searchtxt.getText();
       Node search = bsttree.search(searchelem);
       searchTable(search);
       searchtxt.setText("");
    }//GEN-LAST:event_srchbtnActionPerformed

    private void dltbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltbtnActionPerformed
       searchelem = searchtxt.getText();
       this.temp = bsttree.search(searchelem);
       if(temp != null){
       deleteItem();
       setTable();
       } 
    }//GEN-LAST:event_dltbtnActionPerformed

    private void InsertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertbtnActionPerformed
        insertItem();
        setTable();
        fishnametxt.setText("");
        pricetxt.setText("");
        quantitytxt.setText("");
        ownernametxt.setText("");
        gendertxt.setText("");
        pondtxt.setText("");
        numoffarmerstxt.setText("");
        sourcewatertxt.setText("");
        msystemtxt.setText("");
        csystemtxt.setText("");
        fertilizationtxt.setText("");
        
    }//GEN-LAST:event_InsertbtnActionPerformed

    private void fertilizationtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fertilizationtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fertilizationtxtActionPerformed

    private void csystemtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csystemtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csystemtxtActionPerformed

    private void msystemtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msystemtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msystemtxtActionPerformed

    private void fishnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fishnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fishnametxtActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        setTable();
    }//GEN-LAST:event_viewbtnActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        bsttree.Open();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       bsttree.Save();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        MessageFormat header = new MessageFormat("Fish Product Report");
        MessageFormat footer = new MessageFormat("Page(0,number,integer)");
        
        try {
            ViewTable.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void searchtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtxtActionPerformed

    private void viewrangebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewrangebtnActionPerformed
        String price = searchtxt.getText();
        setRangeTable(price);
    }//GEN-LAST:event_viewrangebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    //SETS THE TABLE 
    public void setTable(){
        
        //TABLE MODEL SETS TO NAME "TABLE"
        DefaultTableModel table = new DefaultTableModel(this.title,0);
        Node current, previous; 
  
        //SETS A TABLE MODEL IF THE ROOT IS NULL
        if (bsttree.root == null){ 
            ViewTable.setModel(table);
            return;
        }
  
        current = bsttree.root; 
        
        //BELOW TRAVERSE THE BST TREE AND INSERTS IT INSIDE A TABLE MODEL
        while (current != null) { 
            if (current.left == null) { 
                String[] data = new String[6];
                data[0] = current.fishname;
                data[1] = current.price;
                data[2] = current.quantity;
                data[3] = current.ownername;
                data[4] = current.pond;
                data[5] = current.numoffarmers;
                table.addRow(data);
                current = current.right; 
            } 
            else { 
                // Find the inorder predecessor of current 
                previous = current.left; 
                while (previous.right != null && previous.right != current) 
                    previous = previous.right; 
  
                // Make current as right child of its inorder predecessor 
                if (previous.right == null) { 
                    previous.right = current; 
                    current = current.left; 
                } 
  
                // Revert the changes made in the 'if' part to restore the  
                // original tree i.e., fix the right child of predecessor
                else { 
                    previous.right = null; 
                    String[] data = new String[6];
                    data[0] = current.fishname;
                    data[1] = current.price;
                    data[2] = current.quantity;
                    data[3] = current.ownername;
                    data[4] = current.pond;
                    data[5] = current.numoffarmers;
                    table.addRow(data);
                    current = current.right;  
                }
            }
        }
        ViewTable.setModel(table);
    }
    
    
    //SETS RANGE TABLE
    public void setRangeTable(String price){
        
        //TABLE MODEL SETS TO NAME "TABLE"
        DefaultTableModel table = new DefaultTableModel(this.title,0);
        Node current, previous; 
  
        //SETS A TABLE MODEL IF THE ROOT IS NULL
        if (bsttree.root == null){ 
            ViewTable.setModel(table);
            return;
        }
  
        //BELOW TRAVERSE THE BST TREE AND INSERTS IT INSIDE A TABLE MODEL
        current = bsttree.root; 
        while (current != null) { 
            if (current.left == null) { 
                
                //THIS STATES HERE THAT IF THE PRICE IS LESSER THAN THE CURRENT PRICE IT WILL ADD.
                if(price.compareTo(current.price) >= 0){
                String[] data = new String[6];
                data[0] = current.fishname;
                data[1] = current.price;
                data[2] = current.quantity;
                data[3] = current.ownername;
                data[4] = current.pond;
                data[5] = current.numoffarmers;
                table.addRow(data);
                }
                current = current.right; 
            } 
            else { 
                // Find the inorder predecessor of current 
                previous = current.left; 
                while (previous.right != null && previous.right != current) 
                    previous = previous.right; 
  
                // Make current as right child of its inorder predecessor 
                if (previous.right == null) { 
                    previous.right = current; 
                    current = current.left; 
                } 
  
                // Revert the changes made in the 'if' part to restore the  
                // original tree i.e., fix the right child of predecessor
                else { 
                    previous.right = null; 
                    if(price.compareTo(current.price) <= 0){
                    String[] data = new String[6];
                    data[0] = current.fishname;
                    data[1] = current.price;
                    data[2] = current.quantity;
                    data[3] = current.ownername;
                    data[4] = current.pond;
                    data[5] = current.numoffarmers;
                    table.addRow(data);
                    }
                    current = current.right; 
                }
            }
        }
        ViewTable.setModel(table);
    }
    
    
    public void searchTable(Node node){
        
        //TABLE MODEL SETS TO NAME "TABLE"
        DefaultTableModel table = new DefaultTableModel(this.title,0); 
  
        //INSERTS TO TABLE IF THE NODE PARAMETER IS NOT NULL
        if(node!=null){
            String[] data = new String[6];
            data[0] = node.fishname;
            data[1] = node.price;
            data[2] = node.quantity;
            data[3] = node.ownername;
            data[4] = node.pond;
            data[5] = node.numoffarmers;
                    table.addRow(data);
            ViewTable.setModel(table);
        }
    }
    
    //INSERT FUNCTION
    public void insertItem(){
        
        //SETS ALL THE TEXT BEING TYPE TO ITS CERTAIN VARIABLES
        fishname = fishnametxt.getText();
        price = pricetxt.getText();
        quantity = quantitytxt.getText();
        ownername = ownernametxt.getText();
        gender = gendertxt.getText();
        pond = pondtxt.getText();
        numoffarmers = numoffarmerstxt.getText();
        sourcewater = sourcewatertxt.getText();
        msystem = msystemtxt.getText();
        csystem = csystemtxt.getText();
        fertilization = fertilizationtxt.getText();
        
       
       //SETS AN ERROR MESSAGE IF SOME OF ITS VARIABLE IS EMPTY
       if(fishname.isEmpty() || price.isEmpty() || quantity.isEmpty() || ownername.isEmpty() || gender.isEmpty() ||
               pond.isEmpty() || numoffarmers.isEmpty() || sourcewater.isEmpty() || msystem.isEmpty() || csystem.isEmpty() ||
               fertilization.isEmpty()){
           JOptionPane.showMessageDialog(null, "Please enter all the information provided", "Error", JOptionPane.ERROR_MESSAGE);
           
       //ADDS ALL THE VALUES TO THE ROOT NODE
       }else{
            bsttree.root = bsttree.insert(bsttree.root, fishname, price, quantity, ownername, gender, 
                                        pond, numoffarmers, sourcewater, msystem, csystem, fertilization);
            JOptionPane.showMessageDialog(null, "Product Added Successfully", "Notification", JOptionPane.WIDTH);
       }
    }
    
    //DELETES FUNCTION
    public void deleteItem(){
        this.price = searchtxt.getText();
            //DELETES THE NODE IF THE TEMP NODE IS NOT NULL
            if(temp != null){
                bsttree.root = bsttree.delete(bsttree.root, price);
                JOptionPane.showMessageDialog(null, "Successful Deleted", "Notification", JOptionPane.WIDTH);
                searchtxt.setText("");
            }
    }
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddPanel;
    private javax.swing.JButton Insertbtn;
    private javax.swing.JTable ViewTable;
    private javax.swing.JTextField csystemtxt;
    private javax.swing.JButton dltbtn;
    private javax.swing.JTextField fertilizationtxt;
    private javax.swing.JTextField fishnametxt;
    private javax.swing.JTextField gendertxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField msystemtxt;
    private javax.swing.JTextField numoffarmerstxt;
    private javax.swing.JTextField ownernametxt;
    private javax.swing.JTextField pondtxt;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JTextField quantitytxt;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JTextField sourcewatertxt;
    private javax.swing.JButton srchbtn;
    private javax.swing.JButton viewbtn;
    private javax.swing.JButton viewrangebtn;
    // End of variables declaration//GEN-END:variables
}
